/**
 * Formulations finales des limites.
 *
 * Une limite nomme seulement l'acte refusé. La raison, la récompense ou la
 * pression qui pourrait faire hésiter appartient au point de bascule, plus
 * tard dans le parcours — jamais au libellé de départ.
 */
export const limitesSimples: Record<string, string> = {
  // Cartes maison
  JV1002: "Mentir à quelqu'un qui me fait confiance",
  JV1003: "Rire de quelqu'un avec le groupe",
  JV1006: "M'attribuer l'idée de quelqu'un d'autre",
  JV1007: "Laisser tomber quelqu'un à la dernière minute",
  JV1012: "Abandonner un projet que d'autres attendent de moi",
  JV1014: "Jouer un personnage",
  JV1015: "Dire oui contre mon avis",
  JV1018: "Blesser quelqu'un exprès",
  JV1019: "Briser la confiance de ma famille",
  JV1020: "Renoncer à mes convictions",
  JV1022: "Voler",
  JV1023: "Faire condamner quelqu'un par un mensonge",
  JV1024: "Dénoncer un proche",
  JV1026: "Utiliser mon corps comme monnaie d'échange",
  JV1028: "Me ridiculiser devant tout le monde",
  JV1029: "Faire porter ma faute à un collègue",
  JV1032: "Couper définitivement les ponts avec ma famille",
  JV1033: "Menacer quelqu'un",
  JV1034: "Signer un faux document",
  JV1035: "Obéir à un ordre injuste",

  // Cartes relues
  LR001: "Humilier quelqu'un devant les autres",
  LR004: "Me servir de quelqu'un",
  LR011: "Mentir au détriment de quelqu'un",
  LR018: "Manipuler quelqu'un par la peur",
  LR020: "Soutenir une chose que je sais fausse",
  LR022: "Trahir un proche",
  LR027: "Faire semblant d'être un ami",
  LR028: "Monter deux personnes l'une contre l'autre",
  LR029: "Sacrifier une amitié importante",
  LR032: "Avantager les miens au détriment de quelqu'un",
  LR033: "Décider à la place de mes proches",
  LR036: "Abandonner une responsabilité familiale",
  LR037: "Contrôler les choix d'un proche par les liens familiaux",
  LR042: "Punir un innocent",
  LR045: "Changer les règles en cours de route",
  LR047: "Profiter de mon statut",
  LR055: "Contrôler les choix de quelqu'un qui dépend de moi",
  LR057: "Punir un choix qui ne nuit à personne",
  LR066: "Briser une règle qui protège les autres",
  LR069: "Détourner un poste de confiance à mon avantage",
  LR071: "Provoquer une chicane volontairement",
  LR073: "Sacrifier une amitié à une niaiserie",
  LR078: "Demander le silence à une personne qui subit une injustice",
  LR081: "Ridiculiser une tradition qui m'est étrangère",
  LR082: "Abandonner ma langue",
  LR089: "Profaner un symbole important",
  LR091: "Profaner ce qui est sacré aux yeux des autres",
  LR093: "Feindre une croyance",
  LR094: "Manipuler quelqu'un par ses croyances",
  LR097: "Renoncer à mes convictions",
  LR099: "Mépriser les croyances sacrées des autres",
  LR100: "Exploiter les croyances sacrées des autres",
  LR103: "Accaparer ce dont je n'ai pas besoin",
  LR104: "Refuser de partager ce que je sais",
  LR109: "M'effacer au bénéfice du groupe",
  LR114: "Abîmer un lieu auquel des gens tiennent",
  LR116: "Détruire un endroit unique",
  LR121: "Abuser de mon autorité",
  LR125: "Faire pression sur quelqu'un qui dépend de moi",
  LR126: "Conserver un titre dont je n'assume plus la responsabilité",
  LR127: "Favoriser mes proches dans une décision commune",
  LR129: "Imposer mes goûts par le pouvoir",
  LR131: "Mettre les autres en danger par bravade",
  LR132: "Faire courir un risque à quelqu'un",
  LR138: "Risquer la sécurité de quelqu'un",
  LR139: "Invoquer la sécurité comme prétexte au contrôle",
  LR142: "Saboter le travail de quelqu'un",
  LR144: "Exiger l'impossible de quelqu'un",
  LR147: "Sacrifier les gens aux résultats",
  LR148: "Bâcler mon travail",
  LR151: "Jouer un personnage",
  LR152: "Renoncer à une part de qui je suis",
  LR154: "Demander à quelqu'un de cacher qui il est",
  LR159: "Me cacher derrière mon groupe",
  LR160: "Couper tous mes liens",
  LR162: "Mettre en danger ceux dont je réponds",
  LR164: "Rabaisser une personne accueillie chez moi",
  LR165: "Fermer le groupe aux nouveaux",
  LR176: "Falsifier le passé",
  LR178: "Empêcher quelqu'un de choisir sa voie au nom des ancêtres",
  LR179: "Garder mon savoir secret",
  LR187: "Cacher ce que je sais",
  LR193: "M'approprier le bien commun",
  LR196: "Accaparer une ressource rare",
  LR198: "M'approprier une ressource vitale à une communauté",
  LR201: "Détruire la réputation de quelqu'un",
  LR205: "Taire une faute grave",
  LR206: "Humilier quelqu'un par des excuses publiques forcées",
  LR209: "Salir mon propre groupe",
  LR210: "Attaquer un innocent au nom de l'honneur des miens",
  LR211: "Refuser tout pardon",
  LR215: "Utiliser une vieille erreur comme moyen de contrôle",
  LR218: "Refuser toute réconciliation",
  LR225: "Demander à quelqu'un de s'effacer au nom du groupe",
  LR229: "Décider à la place de tout le monde",
  LR233: "Sacrifier tout mon temps avec les autres",
  LR234: "Abandonner mes responsabilités",
  LR238: "Repousser une décision sans fin",
  LR241: "Faire souffrir un animal",
};
